# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RG7mvsKnVDlmWqbxJrFtzbKbLrzVbVd
"""



def get_user_profile():
    interest = input("관심 직무를 입력하세요: ")
    industry = input("관심 산업을 입력하세요: ")
    info_need = input("부족한 정보가 무엇인가요? (예: 직무정보/기업문화/스펙/연봉 등): ")
    return interest, industry, info_need  # 입력값들을 반환하여 다음 단계에서 사용할 수 있게 함


# 전문가 데이터베이스 구축 기능
experts = [
    {"name": "김현우", "field": "데이터 분석", "strength": "직무 정보 제공", "industry": "IT"},
    {"name": "박지연", "field": "생산관리", "strength": "현업 경험 전달", "industry": "제조"},
    {"name": "이성훈", "field": "취업 전략", "strength": "로드맵 설계", "industry": "전 분야"},
]


# 전문가 매칭 알고리즘 기능
def match_expert(interest, industry, info_need, experts):
    best = None                 # 가장 적합한 전문가 저장 변수
    best_score = -1             # 비교를 위한 초기 점수

    # 전문가 딕셔너리들을 하나씩 검사
    for e in experts:
        score = 0  # 전문가별로 점수를 0점에서 시작

        # 직무 분야가 같으면 높은 가중치 추가
        if interest in e["field"]:
            score += 2

        # 산업 분야가 같으면 추가 가산점
        if industry == e["industry"]:
            score += 1

        # 부족한 정보가 전문가의 강점과 관련 있을 경우 가산점
        if info_need in e["strength"]:
            score += 1

        # 지금까지 본 전문가 중 가장 높은 점수라면 갱신
        if score > best_score:
            best_score = score
            best = e

    return best   # 최종 결과 반환


# 전문가 상담 시뮬레이션 기능
def simulate_consulting(expert, interest, info_need):
    return f"""
[전문가 {expert['name']}님의 상담]

1. '{interest}' 직무에 대해 가장 먼저 이해해야 할 핵심은 다음입니다:
   → {expert['strength']} 관점에서 실제 현업 정보를 알려드립니다.

2. '{info_need}'에 대한 부족한 부분을 해결하기 위한 첫 단계는 다음입니다:
   → 전문 분야 경험 기반 조언 제공.

3. 다음 단계로 권장하는 준비 로드맵:
   - 기업 분석 방법 가이드
   - 직무 역량 강화 학습 방향 제시
   - 포트폴리오/이력서 개선 포인트 안내
"""


# 상담 결과 요약 및 로드맵 제공 기능
def show_roadmap():
    return """
[맞춤 로드맵]

1단계: 직무 핵심 요구역량 분석
2단계: 프로젝트 경험 추가
3단계: 지원 기업 5개 리스트업
4단계: 면접 대비 전략 수립
"""


# 전체 흐름을 한 번에 실행하는 main() 기능
def main():
    # 1) 사용자 정보 입력받기
    interest, industry, info_need = get_user_profile()

    # 2) 전문가 매칭
    expert = match_expert(interest, industry, info_need, experts)

    # 3) 상담 결과 출력
    if expert:
        print(simulate_consulting(expert, interest, info_need))
        print(show_roadmap())
    else:
        print("적합한 전문가를 찾을 수 없습니다.")


# 프로그램 실행
if __name__ == "__main__":
    main()